version: "3"
services:
  frontend:
    container_name: kogda-virastu-frontend
    build: .
    restart: always
    volumes:
      - ./etc/cofnig/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3002:80"
