const ru = {
  headerLink: 'Главная',
  userEnter: 'Войти',
  newArticle: 'Новая запись',
  settings: 'Настройки',
  exitProfile: 'Выйти',
  mainTitle: 'Когда Вырасту',
  mainSubtitle: 'Каково быть джуном  в турбулентном мире',
  popularTags: 'Популярные тэги',
  popularContent: 'Популярные материалы',
  articleEnter: 'Читать дальше',
  freshContent: 'Свежие материалы',
  comments: 'Комментарии',
  redactArticle: 'Редактировать запись',
  deleteArticle: 'Удалить запись',
  sendComment: 'Отправить комментарий',
  articleName: 'Название статьи',
  articleAbout: 'О чем статья',
  articleImage: 'URL изображения (опционально)',
  articleText: 'Текст статьи',
  tags: 'Теги (через запятую)',
  saveArticle: 'Сохранить запись',
  deletepopuptext: 'Нажимая кнопку «Удалить запись», материал будет удален без возможности восстановления. ',
  subscribe: 'Подписаться',
  unFollow: 'Отписаться',
  register: 'Зарегистрироваться',
  userName: 'Имя пользователя',
  userEmail: 'Email',
  password: 'Пароль',
  urlImage: 'URL изображения профиля',
  newPassword: 'Новый пароль',
  refreshUser: 'Обновить настройки',
  usersettings: 'Ваши настройки',
  publishArticle: 'Опубликовать запись',
  pageMessage: 'Страница не найдена. Чтобы читать блог, перейдите на Главную',

};

const en = {
  headerLink: 'Main Page',
  userEnter: 'Enter',
  newArticle: 'New post',
  settings: 'Settings',
  exitProfile: 'Exit',
  mainTitle: 'When I grow up',
  mainSubtitle: 'What it’s like to be a junior in a turbulent world',
  popularTags: 'Popular tags',
  popularContent: 'Popular content',
  articleEnter: 'Read More',
  freshContent: 'New content',
  comments: 'Comments',
  redactArticle: 'Edit article',
  deleteArticle: 'Delete article',
  sendComment: 'Send comment',
  articleName: 'Article title',
  articleAbout: 'About',
  articleImage: 'URL of images (optional)',
  articleText: 'Article Text',
  tags: 'Tags (with a comma)',
  saveArticle: 'Create article',
  deletepopuptext: 'By clicking «Delete Entry», the material will be removed without the possibility of recovery. ',
  subscribe: 'Subscribe',
  unFollow: 'Unsubscribe',
  register: 'Sign Up',
  userName: 'User Name',
  userEmail: 'Email',
  password: 'Password',
  urlImage: 'User avatar URL',
  newPassword: 'New password',
  refreshUser: 'Update settings',
  usersettings: 'Your setings',
  publishArticle: 'Publish your material',
  pageMessage: 'Page not found. To read blog, go to Home',
};

export { ru, en };
